
/*  ev3_dc.h was generated by yup.py (yupp) 1.0c6
    out of ev3_dc.yu-h
 *//**
 *  \file  ev3_dc.h (ev3_dc.yu-h)
 *  \brief  EV3 DC Motors.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

.macro ENUM_0 name
.equiv \name, 0
.set ENUM_COUNTER, 1
.endm

.macro ENUM_N name
.equiv \name, ENUM_COUNTER
.set ENUM_COUNTER, ENUM_COUNTER + 1
.endm

.macro ENUM_EQ name, value
.equiv \name, \value
.endm

#define DC_DIR  "/sys/class/dc-motor"  /**< Directory of DC motors. */

#define DC_DESC__LIMIT_  DESC_LIMIT  /**< Limit of DC motor descriptors. */

#define DC__NONE_  DC_DESC__LIMIT_  /**< DC motor is not found. */

/**
 *  \brief Vector of DC motor descriptors (filled by \ref ev3_dc_init).
 */
.extern ev3_dc

/**
 *  \brief Identifiers of DC motor types.
 */
ENUM_0  DC_TYPE__NONE_  /* XXX: memset( 0 ) is used */
ENUM_N  RCX_MOTOR

ENUM_N  DC_TYPE__COUNT_  /**< Count of DC motor types. */
ENUM_EQ DC_TYPE__UNKNOWN_, DC_TYPE__COUNT_

/**
 *  \brief Common identifiers of DC motor "command" attribute.
 */
ENUM_0  DC_COMMAND__NONE_

ENUM_N  DC_RUN_FOREVER
ENUM_N  DC_RUN_TIMED
ENUM_N  DC_RUN_DIRECT
ENUM_N  DC_STOP

ENUM_N  DC_COMMAND__COUNT_  /**< Count of DC motor "command" attribute. */
ENUM_EQ DC_COMMAND__UNKNOWN_, DC_COMMAND__COUNT_

/**
 *  \brief Common identifiers of DC motor "polarity" attribute.
 */
ENUM_0  DC_POLARITY__NONE_

ENUM_N  DC_NORMAL
ENUM_N  DC_INVERSED

ENUM_N  DC_POLARITY__COUNT_  /**< Count of DC motor "polarity" attribute. */
ENUM_EQ DC_POLARITY__UNKNOWN_, DC_POLARITY__COUNT_

/**
 *  \brief Common identifiers of DC motor "stop_action" attribute.
 */
ENUM_0  DC_STOP_ACTION__NONE_

ENUM_N  DC_COAST
ENUM_N  DC_BRAKE

ENUM_N  DC_STOP_ACTION__COUNT_  /**< Count of DC motor "stop_action" attribute. */
ENUM_EQ DC_STOP_ACTION__UNKNOWN_, DC_STOP_ACTION__COUNT_

/**
 *  \brief Common identifiers of DC motor "state" attribute.
 */
ENUM_0  DC_STATE__NONE_

ENUM_EQ DC_RUNNING, 0x1L
ENUM_EQ DC_RAMPING, 0x2L

/**
 *  \brief Read "address" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_address

/**
 *  \brief Write "command" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_command

/**
 *  \brief Write "command" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_command

/**
 *  \brief Read "commands" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_commands

/**
 *  \brief Read "driver_name" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_driver_name

/**
 *  \brief Read "duty_cycle" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.

 *  \return Count of read bytes.
 */
.extern get_dc_duty_cycle

/**
 *  \brief Read "duty_cycle_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.

 *  \return Count of read bytes.
 */
.extern get_dc_duty_cycle_sp

/**
 *  \brief Write "duty_cycle_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_duty_cycle_sp

/**
 *  \brief Write "duty_cycle_sp" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_duty_cycle_sp

/**
 *  \brief Read "polarity" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_polarity

/**
 *  \brief Write "polarity" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_polarity

/**
 *  \brief Write "polarity" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_polarity

/**
 *  \brief Read "state" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_state

/**
 *  \brief Write "stop_action" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_stop_action

/**
 *  \brief Write "stop_action" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_stop_action

/**
 *  \brief Read "stop_actions" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_dc_stop_actions

/**
 *  \brief Read "ramp_down_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.

 *  \return Count of read bytes.
 */
.extern get_dc_ramp_down_sp

/**
 *  \brief Write "ramp_down_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_ramp_down_sp

/**
 *  \brief Write "ramp_down_sp" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_ramp_down_sp

/**
 *  \brief Read "ramp_up_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.

 *  \return Count of read bytes.
 */
.extern get_dc_ramp_up_sp

/**
 *  \brief Write "ramp_up_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_ramp_up_sp

/**
 *  \brief Write "ramp_up_sp" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_ramp_up_sp

/**
 *  \brief Read "time_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.

 *  \return Count of read bytes.
 */
.extern get_dc_time_sp

/**
 *  \brief Write "time_sp" attribute of the DC motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern set_dc_time_sp

/**
 *  \brief Write "time_sp" attribute of several DC motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.

 *  \return Count of written bytes.
 */
.extern multi_set_dc_time_sp

/**
 *  \brief Get name of the specified DC motor type.
 *  \param type_inx Index of the DC motor type.
 *  \return Requested value.
 */
.extern ev3_dc_type

/**
 *  \brief Read "driver_name" attribute and get index of the DC motor type.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern get_dc_type_inx

/**
 *  \brief Read DC motor attributes that are required for filling the descriptor.
 *  \param sn Sequence number.
 *  \param desc Buffer for the descriptor.
 *  \return Count of read bytes.
 */
.extern get_dc_desc

/**
 *  \brief Get descriptor of the DC motor.
 *  \param sn Sequence number.
 *  \return Pointer to the DC motor descriptor.
 */
.extern ev3_dc_desc

/**
 *  \brief Get type from the DC motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_dc_desc_type_inx

/**
 *  \brief Get EV3 port from the DC motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_dc_desc_port

/**
 *  \brief Get extended port from the DC motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_dc_desc_extport

/**
 *  \brief Assemble EV3 port name from the DC motor descriptor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \return Requested value.
 */
.extern ev3_dc_port_name

/**
 *  \brief Search of a sequence number of the specified DC motor type.
 *  \param type_inx DC motor type.
 *  \param[out] sn Buffer for the sequence number.
 *  \param from Search initial value.
 *  \return Flag - the DC motor is found.
 */
.extern ev3_search_dc

/**
 *  \brief Search of a sequence number the DC motor by plug-in attributes.
 *  \param port EV3 port.
 *  \param extport Extended port.
 *  \param[out] sn Buffer for the sequence number.
 *  \param from Search initial value.
 *  \return Flag - the DC motor is found.
 */
.extern ev3_search_dc_plugged_in

/**
 *  \brief Get name of the specified DC motor command.
 *  \param command_inx Index of the DC motor command.
 *  \return Requested value.
 */
.extern ev3_dc_command

/**
 *  \brief Write "command" attribute of the DC motor by the index.
 *  \param sn Sequence number.
 *  \param command_inx Index of the DC motor command.
 *  \return Count of written bytes.
 */
.extern set_dc_command_inx

/**
 *  \brief Write "command" attribute of several DC motors by the index.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param command_inx Index of the DC motor command.
 *  \return Count of written bytes.
 */
.extern multi_set_dc_command_inx

/**
 *  \brief Get name of the specified DC motor polarity.
 *  \param polarity_inx Index of the DC motor polarity.
 *  \return Requested value.
 */
.extern ev3_dc_polarity

/**
 *  \brief Read "polarity" attribute of the DC motor and get the index.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern get_dc_polarity_inx

/**
 *  \brief Write "polarity" attribute of the DC motor by the index.
 *  \param sn Sequence number.
 *  \param polarity_inx Index of the DC motor polarity.
 *  \return Count of written bytes.
 */
.extern set_dc_polarity_inx

/**
 *  \brief Write "polarity" attribute of several DC motors by the index.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param polarity_inx Index of the DC motor polarity.
 *  \return Count of written bytes.
 */
.extern multi_set_dc_polarity_inx

/**
 *  \brief Get name of the specified DC motor stop_action.
 *  \param stop_action_inx Index of the DC motor stop_action.
 *  \return Requested value.
 */
.extern ev3_dc_stop_action

/**
 *  \brief Write "stop_action" attribute of the DC motor by the index.
 *  \param sn Sequence number.
 *  \param stop_action_inx Index of the DC motor stop_action.
 *  \return Count of written bytes.
 */
.extern set_dc_stop_action_inx

/**
 *  \brief Write "stop_action" attribute of several DC motors by the index.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param stop_action_inx Index of the DC motor stop_action.
 *  \return Count of written bytes.
 */
.extern multi_set_dc_stop_action_inx

/**
 *  \brief Read "state" attribute of the DC motor and get the flags.
 *  \param sn Sequence number.
 *  \param flags Buffer for the flags.
 *  \return Count of read bytes.
 */
.extern get_dc_state_flags

/**
 *  \brief Detect connected DC motors.
 *  \return Number of found DC motors or -1 in case of an error.
 */
.extern ev3_dc_init

