
/*  ev3_servo.h was generated by yup.py (yupp) 1.0c6
    out of ev3_servo.yu-h 
 *//**
 *  \file  ev3_servo.h (ev3_servo.yu-h)
 *  \brief  EV3 Servo Motors.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#pragma once

#include "enum-asm.h"

#define SERVO_DIR  "/sys/class/servo-motor"  /**< Directory of servo motors. */

#define SERVO_DESC__LIMIT_  DESC_LIMIT  /**< Limit of servo motor descriptors. */

#define SERVO__NONE_  SERVO_DESC__LIMIT_  /**< Servo motor is not found. */

/**
 *  \var EV3_SERVO ev3_servo[ SERVO_DESC__LIMIT_ ]
 *  \brief Vector of servo motor descriptors (filled by \ref ev3_servo_init).
 */
.extern ev3_servo

/**
 *  \brief Identifiers of servo motor types.
 */
ENUM_0  SERVO_TYPE__NONE_  /* XXX: memset( 0 ) is used */
ENUM_N  SERVO_MOTOR

ENUM_N  SERVO_TYPE__COUNT_  /**< Count of servo motor types. */
ENUM_EQ SERVO_TYPE__UNKNOWN_, SERVO_TYPE__COUNT_

/**
 *  \brief Common identifiers of servo motor "command" attribute.
 */
ENUM_0  SERVO_COMMAND__NONE_

ENUM_N  SERVO_RUN
ENUM_N  SERVO_FLOAT

ENUM_N  SERVO_COMMAND__COUNT_  /**< Count of servo motor "command" attribute. */
ENUM_EQ SERVO_COMMAND__UNKNOWN_, SERVO_COMMAND__COUNT_

/**
 *  \brief Common identifiers of servo motor "polarity" attribute.
 */
ENUM_0  SERVO_POLARITY__NONE_

ENUM_N  SERVO_NORMAL
ENUM_N  SERVO_INVERSED

ENUM_N  SERVO_POLARITY__COUNT_  /**< Count of servo motor "polarity" attribute. */
ENUM_EQ SERVO_POLARITY__UNKNOWN_, SERVO_POLARITY__COUNT_

/**
 *  \brief Common identifiers of servo motor "state" attribute.
 */
ENUM_0  SERVO_STATE__NONE_

ENUM_EQ SERVO_RUNNING, 0x1

/**
 *  \fn size_t get_servo_address( uint8_t sn, char *buf, size_t sz )
 *  \brief Read "address" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_servo_address

/**
 *  \fn size_t get_servo_command( uint8_t sn, char *buf, size_t sz )
 *  \brief Read "command" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_servo_command

/**
 *  \fn size_t set_servo_command( uint8_t sn, char *value )
 *  \brief Write "command" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_command

/**
 *  \fn size_t multi_set_servo_command( uint8_t *sn, char *value )
 *  \brief Write "command" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_command

/**
 *  \fn size_t get_servo_driver_name( uint8_t sn, char *buf, size_t sz )
 *  \brief Read "driver_name" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_servo_driver_name

/**
 *  \fn size_t get_servo_max_pulse_sp( uint8_t sn, int *buf )
 *  \brief Read "max_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
		 
 *  \return Count of read bytes.
 */
.extern get_servo_max_pulse_sp

/**
 *  \fn size_t set_servo_max_pulse_sp( uint8_t sn, int value )
 *  \brief Write "max_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_max_pulse_sp

/**
 *  \fn size_t multi_set_servo_max_pulse_sp( uint8_t *sn, int value )
 *  \brief Write "max_pulse_sp" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_max_pulse_sp

/**
 *  \fn size_t get_servo_mid_pulse_sp( uint8_t sn, int *buf )
 *  \brief Read "mid_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
		 
 *  \return Count of read bytes.
 */
.extern get_servo_mid_pulse_sp

/**
 *  \fn size_t set_servo_mid_pulse_sp( uint8_t sn, int value )
 *  \brief Write "mid_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_mid_pulse_sp

/**
 *  \fn size_t multi_set_servo_mid_pulse_sp( uint8_t *sn, int value )
 *  \brief Write "mid_pulse_sp" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_mid_pulse_sp

/**
 *  \fn size_t get_servo_min_pulse_sp( uint8_t sn, int *buf )
 *  \brief Read "min_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
		 
 *  \return Count of read bytes.
 */
.extern get_servo_min_pulse_sp

/**
 *  \fn size_t set_servo_min_pulse_sp( uint8_t sn, int value )
 *  \brief Write "min_pulse_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_min_pulse_sp

/**
 *  \fn size_t multi_set_servo_min_pulse_sp( uint8_t *sn, int value )
 *  \brief Write "min_pulse_sp" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_min_pulse_sp

/**
 *  \fn size_t get_servo_polarity( uint8_t sn, char *buf, size_t sz )
 *  \brief Read "polarity" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_servo_polarity

/**
 *  \fn size_t set_servo_polarity( uint8_t sn, char *value )
 *  \brief Write "polarity" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_polarity

/**
 *  \fn size_t multi_set_servo_polarity( uint8_t *sn, char *value )
 *  \brief Write "polarity" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_polarity

/**
 *  \fn size_t get_servo_position_sp( uint8_t sn, int *buf )
 *  \brief Read "position_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
		 
 *  \return Count of read bytes.
 */
.extern get_servo_position_sp

/**
 *  \fn size_t set_servo_position_sp( uint8_t sn, int value )
 *  \brief Write "position_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_position_sp

/**
 *  \fn size_t multi_set_servo_position_sp( uint8_t *sn, int value )
 *  \brief Write "position_sp" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_position_sp

/**
 *  \fn size_t get_servo_rate_sp( uint8_t sn, int *buf )
 *  \brief Read "rate_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
		 
 *  \return Count of read bytes.
 */
.extern get_servo_rate_sp

/**
 *  \fn size_t set_servo_rate_sp( uint8_t sn, int value )
 *  \brief Write "rate_sp" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern set_servo_rate_sp

/**
 *  \fn size_t multi_set_servo_rate_sp( uint8_t *sn, int value )
 *  \brief Write "rate_sp" attribute of several servo motors.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param value Attribute value.
		 
 *  \return Count of written bytes.
 */
.extern multi_set_servo_rate_sp

/**
 *  \fn size_t get_servo_state( uint8_t sn, char *buf, size_t sz )
 *  \brief Read "state" attribute of the servo motor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \param sz Buffer size.
 *  \return Count of read bytes.
 */
.extern get_servo_state

/**
 *  \fn const char *ev3_servo_type( INX_T type_inx )
 *  \brief Get name of the specified servo motor type.
 *  \param type_inx Index of the servo motor type.
 *  \return Requested value.
 */
.extern ev3_servo_type

/**
 *  \fn INX_T get_servo_type_inx( uint8_t sn )
 *  \brief Read "driver_name" attribute and get index of the servo motor type.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern get_servo_type_inx

/**
 *  \fn size_t get_servo_desc( uint8_t sn, EV3_SERVO *desc )
 *  \brief Read servo motor attributes that are required for filling the descriptor.
 *  \param sn Sequence number.
 *  \param desc Buffer for the descriptor.
 *  \return Count of read bytes.
 */
.extern get_servo_desc

/**
 *  \fn EV3_SERVO *ev3_servo_desc( uint8_t sn )
 *  \brief Get descriptor of the servo motor.
 *  \param sn Sequence number.
 *  \return Pointer to the servo motor descriptor.
 */
.extern ev3_servo_desc

/**
 *  \fn INX_T ev3_servo_desc_type_inx( uint8_t sn )
 *  \brief Get type from the servo motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_servo_desc_type_inx

/**
 *  \fn uint8_t ev3_servo_desc_port( uint8_t sn )
 *  \brief Get EV3 port from the servo motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_servo_desc_port

/**
 *  \fn uint8_t ev3_servo_desc_extport( uint8_t sn )
 *  \brief Get extended port from the servo motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_servo_desc_extport

/**
 *  \fn uint8_t ev3_servo_desc_addr( uint8_t sn )
 *  \brief Get I2C address from the servo motor descriptor.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern ev3_servo_desc_addr

/**
 *  \fn char *ev3_servo_port_name( uint8_t sn, char *buf )
 *  \brief Assemble EV3 port name from the servo motor descriptor.
 *  \param sn Sequence number.
 *  \param[out] buf Buffer for result.
 *  \return Requested value.
 */
.extern ev3_servo_port_name

/**
 *  \fn bool ev3_search_servo( INX_T type_inx, uint8_t *sn, uint8_t from )
 *  \brief Search of a sequence number of the specified servo motor type.
 *  \param type_inx Servo motor type.
 *  \param[out] sn Buffer for the sequence number.
 *  \param from Search initial value.
 *  \return Flag - the servo motor is found.
 */
.extern ev3_search_servo

/**
 *  \fn bool ev3_search_servo_plugged_in( uint8_t port, uint8_t extport, uint8_t *sn, uint8_t from )
 *  \brief Search of a sequence number the servo motor by plug-in attributes.
 *  \param port EV3 port.
 *  \param extport Extended port.
 *  \param[out] sn Buffer for the sequence number.
 *  \param from Search initial value.
 *  \return Flag - the servo motor is found.
 */
.extern ev3_search_servo_plugged_in

/**
 *  \fn const char *ev3_servo_command( INX_T command_inx )
 *  \brief Get name of the specified servo motor command.
 *  \param command_inx Index of the servo motor command.
 *  \return Requested value.
 */
.extern ev3_servo_command

/**
 *  \fn INX_T get_servo_command_inx( uint8_t sn )
 *  \brief Read "command" attribute of the servo motor and get the index.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern get_servo_command_inx

/**
 *  \fn size_t set_servo_command_inx( uint8_t sn, INX_T command_inx )
 *  \brief Write "command" attribute of the servo motor by the index.
 *  \param sn Sequence number.
 *  \param command_inx Index of the servo motor command.
 *  \return Count of written bytes.
 */
.extern set_servo_command_inx

/**
 *  \fn size_t multi_set_servo_command_inx( uint8_t *sn, INX_T command_inx )
 *  \brief Write "command" attribute of several servo motors by the index.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param command_inx Index of the servo motor command.
 *  \return Count of written bytes.
 */
.extern multi_set_servo_command_inx

/**
 *  \fn const char *ev3_servo_polarity( INX_T polarity_inx )
 *  \brief Get name of the specified servo motor polarity.
 *  \param polarity_inx Index of the servo motor polarity.
 *  \return Requested value.
 */
.extern ev3_servo_polarity

/**
 *  \fn INX_T get_servo_polarity_inx( uint8_t sn )
 *  \brief Read "polarity" attribute of the servo motor and get the index.
 *  \param sn Sequence number.
 *  \return Requested value.
 */
.extern get_servo_polarity_inx

/**
 *  \fn size_t set_servo_polarity_inx( uint8_t sn, INX_T polarity_inx )
 *  \brief Write "polarity" attribute of the servo motor by the index.
 *  \param sn Sequence number.
 *  \param polarity_inx Index of the servo motor polarity.
 *  \return Count of written bytes.
 */
.extern set_servo_polarity_inx

/**
 *  \fn size_t multi_set_servo_polarity_inx( uint8_t *sn, INX_T polarity_inx )
 *  \brief Write "polarity" attribute of several servo motors by the index.
 *  \param sn Vector of sequence numbers ending with DESC_LIMIT.
 *  \param polarity_inx Index of the servo motor polarity.
 *  \return Count of written bytes.
 */
.extern multi_set_servo_polarity_inx

/**
 *  \fn size_t get_servo_state_flags( uint8_t sn, FLAGS_T *flags )
 *  \brief Read "state" attribute of the servo motor and get the flags.
 *  \param sn Sequence number.
 *  \param flags Buffer for the flags.
 *  \return Count of read bytes.
 */
.extern get_servo_state_flags

/**
 *  \fn int ev3_servo_init( void )
 *  \brief Detect connected servo motors.
 *  \return Number of found servo motors or -1 in case of an error.
 */
.extern ev3_servo_init

